version: '3'

services:
  web:
    build: .
    command: gunicorn wordstat_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./logs:/app/logs
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app_network

  celery:
    build: .
    command: celery -A wordstat_project worker -l info -c 3
    volumes:
      - .:/app
      - ./logs:/app/logs
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app_network

  redis:
    image: redis:alpine
    networks:
      - app_network
    volumes:
      - ./logs:/var/log/redis
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles
      - ./uploads:/app/uploads 
      - ./logs:/var/log/nginx
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge